version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: kornpassorn-postgres
    environment:
      POSTGRES_DB: kornpassorn_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/nestjs/_content/database:/docker-entrypoint-initdb.d
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: kornpassorn-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@kornpassorn.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
